export const QUESTIONS_FETCH_START = 'QUESTIONS_FETCH_START';
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';
export const QUESTIONS_FETCH_FAIL = 'QUESTIONS_FETCH_FAIL';

export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';

export const ACCEPT_ANSWER = 'ACCEPT_ANSWER';

export const STOP_TIMER = 'STOP_TIMER';

export const RESET_QUIZ = 'RESET_QUIZ';
